# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cwjbZPzRqslM-ndjIuOIKnHecSEjI2l0
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.offline import init_notebook_mode
import matplotlib.pyplot as plt
# %matplotlib inline
from wordcloud import wordcloud, ImageColorGenerator

data=pd.read_csv("/content/indian_food.csv")
data

data.head()

data.columns

data.info()

data.isnull().any()

data.isnull().sum()

data=data.replace(-1, np.nan)
data=data.replace('-1',np.nan)
data.isnull().sum()

data.shape

pie_data=data.diet.value_counts().reset_index()
pie_data.columns=["diet","count"]
fig= px.pie(pie_data, values='count',names='diet',title='Proportion of Vegeterian and Non-Vegetarian dishes', color_discrete_sequence=['green','red'])
fig.show()

cooking_time=data[['cook_time','name']]
cooking_time.head()

cooking_time=cooking_time.sort_values(['cook_time'],ascending=True)

ten_cook_quickly=cooking_time.head(10)
fig=px.bar(ten_cook_quickly, x="cook_time",y="name", title="dishes based on cooking time",color_discrete_sequence=['red'])

fig.show()